import threading
import time

import httpx

from openai import OpenAI
from oci_genai_auth import (
    OciInstancePrincipalAuth,
    OciUserPrincipalAuth,
)

from config import (
    OCI_AUTH_MODE,
    OCI_BASE_URL,
    OCI_PROFILE,
    OCI_PROJECT_ID,
    MODEL_NAME,
)


class LLMClient:
    def __init__(
        self,
        model: str | None = None,
    ):
        self.model = (
            str(model).strip()
            if model
            else MODEL_NAME
        )

        # ==================================================
        # AUTHENTICATION
        # ==================================================
        #
        # Local machine:
        # OCI_AUTH_MODE=config
        #
        # Uses a normal OCI API signing-key profile:
        # [DEFAULT]
        # user=...
        # fingerprint=...
        # tenancy=...
        # region=...
        # key_file=...
        #
        # OCI Compute:
        # OCI_AUTH_MODE=instance_principal
        #
        # NOTE:
        # OciSessionAuth is NOT used here because it expects
        # a security_token_file generated by OCI CLI session
        # authentication. A normal API-key profile should use
        # OciUserPrincipalAuth instead.
        # ==================================================

        auth_mode = (
            OCI_AUTH_MODE
            .strip()
            .lower()
        )

        if auth_mode not in {
            "auto",
            "config",
            "instance_principal",
        }:
            raise ValueError(
                "OCI_AUTH_MODE must be one of: "
                "auto, config, instance_principal"
            )

        if auth_mode == "config":

            http_auth = (
                OciUserPrincipalAuth(
                    profile_name=OCI_PROFILE
                )
            )

            print(
                "LLM authentication: "
                f"OCI user principal profile "
                f"'{OCI_PROFILE}'"
            )

        elif auth_mode == "instance_principal":

            http_auth = (
                OciInstancePrincipalAuth()
            )

            print(
                "LLM authentication: "
                "Instance Principal"
            )

        else:

            try:

                http_auth = (
                    OciInstancePrincipalAuth()
                )

                print(
                    "LLM authentication: "
                    "Instance Principal "
                    "(auto-detected)"
                )

            except Exception as instance_error:

                print(
                    "Instance Principal unavailable. "
                    "Using local OCI user principal."
                )

                print(
                    "Instance Principal reason: "
                    f"{type(instance_error).__name__}: "
                    f"{instance_error}"
                )

                http_auth = (
                    OciUserPrincipalAuth(
                        profile_name=OCI_PROFILE
                    )
                )

                print(
                    "LLM authentication: "
                    f"OCI user principal profile "
                    f"'{OCI_PROFILE}'"
                )

        # ==================================================
        # HTTP / OPENAI CLIENT
        # ==================================================

        self.http_client = httpx.Client(
            auth=http_auth,
            timeout=httpx.Timeout(
                connect=20.0,
                read=600.0,
                write=120.0,
                pool=30.0,
            ),
            limits=httpx.Limits(
                max_connections=30,
                max_keepalive_connections=15,
            ),
        )

        self.client = OpenAI(
            base_url=OCI_BASE_URL,
            api_key="not-used",
            project=OCI_PROJECT_ID,
            http_client=self.http_client,
        )

    def ask(
        self,
        prompt: str,
        *,
        model: str | None = None,
        label: str | None = None,
    ) -> str:
        if not prompt or not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        request_model = (
            str(model).strip()
            if model
            else self.model
        )

        started = (
            time.perf_counter()
        )

        thread_name = (
            threading
            .current_thread()
            .name
        )

        request_label = (
            label or "LLM"
        )

        print(
            f"[{request_label}] "
            "Starting request | "
            f"model={request_model} | "
            f"prompt_chars={len(prompt)} | "
            f"thread={thread_name}"
        )

        try:

            response = (
                self.client.responses.create(
                    model=request_model,
                    input=prompt,
                )
            )

            output_text = (
                response.output_text
                or ""
            )

            elapsed = (
                time.perf_counter()
                - started
            )

            print(
                f"[{request_label}] "
                "Completed | "
                f"{elapsed:.2f}s | "
                f"output_chars={len(output_text)}"
            )

            return output_text

        except Exception:

            elapsed = (
                time.perf_counter()
                - started
            )

            print(
                f"[{request_label}] "
                "FAILED after "
                f"{elapsed:.2f}s"
            )

            raise

    def close(
        self,
    ):
        self.http_client.close()
